name: On push

on:
  push:

jobs:
  process-push:
    name: Process push to a branch
    permissions:
        contents: write # this must be set to 'write' in order for the workflow to add a tag
    uses: ./.github/workflows/gitflow_on_push.yml
