name: Application image feature branch push

on:
  workflow_call:

jobs:
  process-push:
    name: Process push to feature branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0
      - name: show shared workflow feature
        run: echo This is feature-one of shared workflow.
      - name: Get the semantic version
        id: semantic_version
        uses: paulhatch/semantic-version@v5.4.0
      # - name: Show greeting
      #   uses: keeonline/poc-github-app-pipelines/.github/actions/hello-world@feature-one
      # - name: Show greeting
      #   uses: ./.github/workflows/helper_hello_world.yml
      # - name: Get the feature branch version
      #   id: feature_branch_version
      #   run: echo "value=${{ steps.semantic_version.outputs.version_tag }}+${{ steps.semantic_version.outputs.increment }}-${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
      # - name: Show the feature version
      #   run: 'echo This is the feature version that any job or step in the workflow can now use: ${{steps.feature_branch_version.outputs.value}}'
      # - name: Linting
      #   run: 'echo Not Implemented: linting action'
      # - name: Build
      #   run: 'echo Not Implemented: build action'
      # - name: Publish arterfact
      #   run: 'echo Not Implemented: publish action'
  