name: Develop push

# on:
#   push:
#     branches: 
#       - develop

on:
  workflow_call:

jobs:
  process-push:
    name: Execute push to develop branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get the semantic version
        id: semantic_version
        uses: paulhatch/semantic-version@v5.4.0
      - name: Get the develop branch version
        id: develop_branch_version
        run: echo "value=${{ steps.semantic_version.outputs.version_tag }}+${{ steps.semantic_version.outputs.increment }}-${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
      - name: Show the develop version
        run: 'echo This is the develop version that any job or step in the workflow can now use: ${{steps.develop_branch_version.outputs.value}}'
      - name: Linting
        run: 'echo Not Implemented: linting action'
      - name: Build
        run: 'echo Not Implemented: build action'
      - name: Publish artefact
        run: 'echo Not Implemented: publish action'
      - name: System Integration testing (SIT)
        run: 'echo Not Implemented: SIT action'


