name: Hotfix branch push

# on:
#   push:
#     branches:
#       - 'hotfix*'

on:
  workflow_call:

jobs:
  process-push:
    name: Process push to hotfix branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get the semantic version
        id: semantic_version
        uses: paulhatch/semantic-version@v5.4.0
      - name: Get the hotfix branch version
        id: hotfix_branch_version
        run: echo "value=${{ steps.semantic_version.outputs.version_tag }}+${{ steps.semantic_version.outputs.increment }}-${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
      - name: Linting
        run: 'echo Not Implemented: linting action'
      - name: Build
        run: 'echo Not Implemented: build action'
      - name: Publish artefact
        run: 'echo Not Implemented: publish action'


