name: Gitflow PR

# on:
#   pull_request:

on:
  workflow_call:
  
jobs:
  get-branch-type:
    name: Process PR to a Gitflow branch
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.branch_type.outputs.value }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Determine branch type
        id: branch_type
        run: |
          if [[ ${GITHUB_BASE_REF} == main ]] ; then
            echo "value=main" >> $GITHUB_OUTPUT
          elif [[ ${GITHUB_BASE_REF} == develop ]] ; then
            echo "value=develop" >> $GITHUB_OUTPUT
          else
            echo "value=other" >> $GITHUB_OUTPUT
          fi
  pr-to-develop:
    name: PR to develop
    needs: [get-branch-type]
    if: needs.get-branch-type.outputs.value == 'develop'
    uses: ./.github/workflows/gitflow_develop_on_pull_request.yml
  pr-to-main:
    name: PR to main
    needs: [get-branch-type]
    if: needs.get-branch-type.outputs.value == 'main'
    uses: ./.github/workflows/gitflow_main_on_pull_request.yml
        