name: Gitflow push

# on:
#   push:

on:
  workflow_call:
  
jobs:
  get-branch-type:
    name: Process push to a Gitflow branch
    runs-on: ubuntu-latest
    permissions:
      contents: write # this must be set to 'write' in order for the workflow to add a tag
    outputs:
      value: ${{ steps.branch_type.outputs.value }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Determine branch type
        id: branch_type
        run: |
          if [[ ${GITHUB_REF_NAME} == main ]] ; then
            echo "value=main" >> $GITHUB_OUTPUT
          elif [[ ${GITHUB_REF_NAME} == develop ]] ; then
            echo "value=develop" >> $GITHUB_OUTPUT
          elif [[ ${GITHUB_REF_NAME} == release* ]] ; then
            echo "value=release" >> $GITHUB_OUTPUT
          elif [[ ${GITHUB_REF_NAME} == hotfix* ]] ; then
            echo "value=hotfix" >> $GITHUB_OUTPUT
          else
            echo "value=feature" >> $GITHUB_OUTPUT
          fi
  push-to-develop:
    name: Push to develop
    needs: [get-branch-type]
    if: needs.get-branch-type.outputs.value == 'develop'
    uses: ./.github/workflows/gitflow_develop_on_push.yml
  push-to-main:
    name: Push to main
    needs: [get-branch-type]
    if: needs.get-branch-type.outputs.value == 'main'
    uses: ./.github/workflows/gitflow_main_on_push.yml
  push-to-release:
    name: Push to release
    needs: [get-branch-type]
    if: needs.get-branch-type.outputs.value == 'release'
    uses: ./.github/workflows/gitflow_release_on_push.yml
  push-to-hotfix:
    name: Push to hotfix
    needs: [get-branch-type]
    if: needs.get-branch-type.outputs.value == 'hotfix'
    uses: ./.github/workflows/gitflow_hotfix_on_push.yml
  push-to-feature:
    name: Push to feature
    needs: [get-branch-type]
    if: needs.get-branch-type.outputs.value == 'feature'
    uses: ./.github/workflows/gitflow_feature_on_push.yml
        