name: Release branch push

# on:
#   push:
#     branches:
#       - 'release*'

on:
  workflow_call:

jobs:
  process-push:
    name: Process push to release branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get the semantic version
        id: semantic_version
        uses: paulhatch/semantic-version@v5.4.0
      - name: Get the release branch version
        id: release_branch_version
        run: echo "value=${{ steps.semantic_version.outputs.version_tag }}+${{ steps.semantic_version.outputs.increment }}-${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
      - name: Show the release branch version
        run: 'echo This is the release branch version that any job or step in the workflow can now use: ${{steps.release_branch_version.outputs.value}}'
      - name: Build
        run: 'echo Not Implemented: build action'
      - name: Publish arterfact
        run: 'echo Not Implemented: publish action'
      - name: System Integration testing (SIT)
        run: 'echo Not Implemented: SIT action'
      - name: Dynamic Application Security Testing (DAST) 
        run: 'echo Not Implemented: DAST step'
      - name: Performance Test (PT) 
        run: 'echo Not Implemented: PT step'