name: Main push (this repo)

on:
  push:
    branches:
      - main

jobs:
  process-push:
    name: Process push to main
    runs-on: ubuntu-latest
    permissions:
      contents: write # this must be set to 'write' in order for the workflow to add a tag
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get the semantic version
        id: semantic_version
        uses: paulhatch/semantic-version@v5.4.0
      - name: Get the release version
        id: release_version
        run: echo "value=${{ steps.semantic_version.outputs.version_tag }}" >> $GITHUB_OUTPUT
      - name: Show the release version
        run: 'echo This is the release version that will be tagged on main: ${{steps.release_version.outputs.value}}'
      - name: Tag main with the release version
        uses: rickstaa/action-create-tag@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{steps.release_version.outputs.value}}
